#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'filesystem_stdio_client'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('FILESYSTEM_STDIO_EXPORTS',1)
	conf.define('DONT_PROTECT_FILEIO_FUNCTIONS',1)
#	conf.define('PROTECTED_THINGS_ENABLE',1)
	conf.define('_USE_32BIT_TIME_T',1)
	conf.define('SUPPORT_PACKED_STORE',1)

def build(bld):
	source = [
		'basefilesystem.cpp',
		'basefilesystemasync.cpp',
		'filetracker.cpp',
		'filesystemasync.cpp',#       [!$PS3]
		'filesystem_stdio.cpp',
		'../public/kevvaluescompiler.cpp',# [!$PS3]
		'../public/zip_utils.cpp',#  [!$PS3]
		'QueuedLoader.cpp',
		'linux_support.cpp',#         [$POSIX]
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	defines = []

	libs = ['tier0_client','vpklib_client','tier1_client','interfaces_client','tier2_client','vstdlib_client']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

