#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'mathlib_extended'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('MATHLIB_LIB',1)

def build(bld):
	source = [
		'../disjoint_set_forest.cpp',
		'../dynamictree.cpp',
		'../eigen.cpp',
		'../simdvectormatrix.cpp',
		'../femodel.cpp',
		'../femodelbuilder.cpp',
		'../feagglomerator.cpp',
		'../svd.cpp',
		'../transform.cpp',
		'../femodeldesc.cpp',
		'../softbody.cpp',
		'../softbodyenvironment.cpp'
	]	

	includes = [
		'..',
		'../../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/mathlib'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

