#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bzip2'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'blocksort.c',
		'bzip2.c',
		'bzlib.c',
		'compress.c',
		'crctable.c',
		'decompress.c',
		'huffman.c',
		'randtable.c'
	]

	includes = [
		'.'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

