#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'responserules_runtime'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'rrrlib.cpp',
		'response_types.cpp',
		'response_types_internal.cpp',
		'response_system.cpp',
		'rr_speechconcept.cpp',
		'rr_response.cpp',
		'criteriaset.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

