#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vgui_surfacelib'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'BitmapFont.cpp',
		'FontAmalgam.cpp',
		'fontmanager.cpp',
		'FontEffects.cpp',
		'fonttexturecache.cpp',
		'texturedictionary.cpp',
		'linuxfont.cpp'#		[$LINUXALL]
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
	] + bld.env.INCLUDES_FT2

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
