name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt update && sudo apt upgrade -y && sudo apt install -y git build-essential libsdl2-mixer-dev libsdl2-dev libopenal-dev libcurlpp-dev libssl-dev libfontconfig1-dev libcurl4-openssl-dev net-tools wget unzip zip
        ./waf configure -T release --64bits
        ./waf build -j2
        find ./build -type f -name "*.o" -delete
        find ./build -type d -empty -delete
        zip -r build-hl2-32.zip build
    - uses: actions/upload-artifact@v3
      with:
        name: CS:GO SDK 2017
        path: ./*.zip
