name: Linux

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        sudo apt-get update && sudo apt install -y git build-essential libsdl2-mixer-dev libsdl2-dev libopenal-dev libcurlpp-dev libssl-dev libfontconfig1-dev libcurl4-openssl-dev net-tools
        ./waf configure -T debug --64bits --prefix=/home/runner/work/csgo-sdk-2017/csgo-sdk-2017/csgo-release
        ./waf install -j4

    - uses: actions/upload-artifact@v3
      with:
            name: Debug x64
            path: /home/runner/work/csgo-sdk-2017/csgo-sdk-2017/csgo-release
