#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'soundsystem_lowlevel'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'asanstubs.cpp',
		'device_sdl.cpp',
		'device_null.cpp',
		'mix.cpp',
		'simple_filter.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

